ALTER TABLE public.students
  ADD COLUMN IF NOT EXISTS admission_type text DEFAULT 'New',
  ADD COLUMN IF NOT EXISTS receipt_no text,
  ADD COLUMN IF NOT EXISTS admission_date date DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS bangla_name text,
  ADD COLUMN IF NOT EXISTS birth_registration_no text,
  ADD COLUMN IF NOT EXISTS special_disease text,
  ADD COLUMN IF NOT EXISTS previous_institution text,
  ADD COLUMN IF NOT EXISTS father_nid text,
  ADD COLUMN IF NOT EXISTS father_occupation text,
  ADD COLUMN IF NOT EXISTS father_bangla_name text,
  ADD COLUMN IF NOT EXISTS mother_nid text,
  ADD COLUMN IF NOT EXISTS mother_occupation text,
  ADD COLUMN IF NOT EXISTS mother_bangla_name text,
  ADD COLUMN IF NOT EXISTS permanent_village text,
  ADD COLUMN IF NOT EXISTS permanent_post text,
  ADD COLUMN IF NOT EXISTS permanent_upazila text,
  ADD COLUMN IF NOT EXISTS permanent_district text,
  ADD COLUMN IF NOT EXISTS present_village text,
  ADD COLUMN IF NOT EXISTS present_post text,
  ADD COLUMN IF NOT EXISTS present_upazila text,
  ADD COLUMN IF NOT EXISTS present_district text;